spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: sa
    url: jdbc:log4jdbc:mysql://localhost:3306/loanapplication
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect